### ISSUE TITLE
Error installing MidnightSky0.7.apk

### ISSUE THREAD

**Issue by vinnyA3** [AdrianaVecc/MidnightSkyVR#1]
Error installing MidnightSky0.7apk on Samsung Galaxy s4. Getting following err message:

**Describe Error:**
There is a problem parsing the package

**Comment by AdrianaVecc** [comment]
Thanks for letting me know, @vinnyA3. Please could you share some error logs?
What is the OS version of your device?

**Comment by vinnyA3** [comment]
I can't seem to find any error logs ( not sure where to find them).  My current OS: 5.0.1 'Lollipop'.  Samsung is no longer updating the OS for my phone.  I did, however, install the 0.6apk and that is working just fine now.

**Comment by AdrianaVecc** [comment]
In version 0.7, the minimum Android API supported went from 4.4 to 6.0 to accommodate new features :(
I can try to build retro-compatible features in the future for greater accessibility. Adding to the backlog but not sure when it can be tackled...

To find device error log, plug your Android phone to your laptop and launch Android Studio or Intelli-J, it will display the logs.
